---
sudo: false
branches:
  only:
  - master
language: ruby
bundler_args: --without development
script:
  - bundle exec rake validate
  - bundle exec rake lint
  - bundle exec rake spec SPEC_OPTS='--format documentation'
rvm:
  - 1.8.7
  - 1.9.3
  - 2.1.6
matrix:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
notification:
  email: false
