---
sudo: false
branches:
  only:
  - master
language: ruby
script: "bundle exec rake validate lint spec"
matrix:
  fast_finish: true
  include:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 3.0"
    - rvm: 2.1.6
      env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
    - rvm: 2.1.6
      env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
notification:
  email: false
