---
sudo: false
branches:
  only:
  - master
language: ruby
bundler_args: --without development
script:
  - bundle exec rake validate
  - bundle exec rake lint
  - bundle exec rake spec SPEC_OPTS='--format documentation'
rvm:
  - 2.1.9
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.8.0"
    - PUPPET_GEM_VERSION="~> 3.8.0" FUTURE_PARSER="yes"
    - PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
matrix:
  exclude:
    - rvm: 2.1.6
      env: PUPPET_GEM_VERSION="~> 3.2.0"
notification:
  email: false
